backend: 
  name: git-gateway
  branch: master

media_folder: static/assets 

public_folder: /assets

collections:
  - name: blog-posts 
    label: Blog Posts 
    label_singular: Blog Post 
    folder: content/blog
    create: true 
    fields:
      - { name: date, label: Date, widget: datetime}
      - { name: title, label: Blog Title }
      - { name: content, label: Blog Content }
      - { name: url, label: Url }